/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-error": "#690005",
        "on-tertiary": "#28313c",
        "primary-container": "#62f9ee",
        "tertiary": "#ffffff",
        "on-secondary-container": "#a1fcf7",
        "on-tertiary-fixed": "#131c27",
        "on-surface-variant": "#bacac7",
        "primary": "#ffffff",
        "on-secondary-fixed": "#00201f",
        "surface-tint": "#3cdcd1",
        "secondary": "#7bd6d1",
        "primary-fixed": "#62f9ee",
        "on-surface": "#e3e2e8",
        "on-tertiary-fixed-variant": "#3e4753",
        "surface-dim": "#121317",
        "outline-variant": "#3c4948",
        "on-error-container": "#ffdad6",
        "secondary-container": "#007774",
        "secondary-fixed-dim": "#7bd6d1",
        "on-primary-fixed-variant": "#00504b",
        "background": "#121317",
        "surface-container-lowest": "#0d0e12",
        "surface-container-highest": "#343439",
        "primary-fixed-dim": "#3cdcd1",
        "inverse-primary": "#006a64",
        "inverse-on-surface": "#2f3035",
        "surface-container-low": "#1a1b20",
        "on-primary-fixed": "#00201e",
        "error-container": "#93000a",
        "on-secondary-fixed-variant": "#00504d",
        "secondary-fixed": "#98f2ed",
        "surface": "#121317",
        "error": "#ffb4ab",
        "tertiary-container": "#dae3f2",
        "on-tertiary-container": "#5c6572",
        "on-secondary": "#003735",
        "surface-bright": "#38393e",
        "inverse-surface": "#e3e2e8",
        "surface-container-high": "#292a2e",
        "on-primary-container": "#00716b",
        "on-background": "#e3e2e8",
        "on-primary": "#003734",
        "surface-variant": "#343439",
        "surface-container": "#1f1f24",
        "outline": "#859491",
        "tertiary-fixed": "#dae3f2",
        "tertiary-fixed-dim": "#bec7d6",
        "brand-yellow": "#d4af37",
        "brand-blue": "#0a4b8f"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "card-gap": "48px",
        "gutter": "24px",
        "unit-lg": "24px",
        "section-padding": "80px",
        "unit-md": "16px",
        "container-max": "1200px",
        "unit-xs": "4px",
        "unit-sm": "8px"
      },
      fontFamily: {
        "headline-sm": ["Hanken Grotesk"],
        "display-lg-mobile": ["Hanken Grotesk"],
        "body-lg": ["Hanken Grotesk"],
        "headline-md": ["Hanken Grotesk"],
        "display-lg": ["Hanken Grotesk"],
        "label-mono": ["JetBrains Mono"],
        "body-md": ["Hanken Grotesk"],
        "sans": ['Hanken Grotesk', 'sans-serif'],
      },
      fontSize: {
        "headline-sm": ["24px", {"lineHeight": "1.3", "fontWeight": "600"}],
        "display-lg-mobile": ["36px", {"lineHeight": "1.2", "fontWeight": "800"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "headline-md": ["32px", {"lineHeight": "1.2", "fontWeight": "700"}],
        "display-lg": ["56px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "800"}],
        "label-mono": ["14px", {"lineHeight": "1.0", "letterSpacing": "0.05em", "fontWeight": "500"}],
        "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
